name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      # Trigger deploy on manifest change
      - 'manifest.json'

jobs:
  Chrome:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pack extension
      uses: TheDoctor0/zip-release@0.4.1
      with:
        filename: ./TabsAside.zip
        exclusions: '.git/* .vscode/* .github/* *.md'

    - name: Publish to Chrome Webstore
      uses: SebastienGllmt/chrome-addon@v3
      with:
        extension: mgmjbodjgijnebfgohlnjkegdpbdjgin
        zip: ./TabsAside.zip
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

    - name: Drop artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 'Chrome Artifacts'
        path: ./TabsAside.zip